---
- name: 'Create Consul service definition'
  include_role: name=consul-service
  vars:
    consul_config_name: '{{ nim_codex_consul_service_file_name }}'
    consul_services:
      - id:   '{{ nim_codex_service_name }}'
        name: '{{ nim_codex_consul_service_name }}'
        port: '{{ nim_codex_listening_port }}'
        address: '{{ nim_codex_public_address }}'
        tags: ['{{ env }}.{{ stage }}', 'codex', 'storage']
        checks:
          - name: '{{ nim_codex_service_name }}-health'
            type: 'http'
            http: 'http://localhost:{{ nim_codex_rest_port }}/api/codex/v1/debug/info'
