---
- name: Open Libp2p ports in iptables
  include_role: name=open-ports
  vars:
    open_ports_default_comment: '{{ nim_codex_service_name }}'
    open_ports_default_chain: 'SERVICES'
    open_ports_list:
      - { port: '{{ nim_codex_listening_port }}', protocol: 'tcp' }
      - { port: '{{ nim_codex_rest_port }}',      chain: 'VPN', ipset: '{{ env }}.{{ stage }}' }
